version: '3.9'
services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /home/adam/web/default:/usr/share/nginx/html:ro

  adam:
    image: nginx:latest
    container_name: adam
    depends_on:
      - proxy
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=adam.myvirtualmachine.com
      - VIRTUAL_PORT=80
    volumes:
      - /home/adam/web/adam:/usr/share/nginx/html:ro
        
  keelan:
    image: nginx:latest
    container_name: keelan
    depends_on:
      - proxy
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=keelan.myvirtualmachine.com
      - VIRTUAL_PORT=80
    volumes:
      - /home/adam/web/keelan:/usr/share/nginx/html:ro
        
  first:
    image: nginx:latest
    container_name: first
    depends_on:
      - proxy
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=first.myvirtualmachine.com
      - VIRTUAL_PORT=80
    volumes:
      - /home/adam/web/first:/usr/share/nginx/html:ro

  root:
    image: nginx:latest
    container_name: root
    depends_on:
      - proxy
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=myvirtualmachine.com
      - VIRTUAL_PORT=80
    volumes:
      - /home/adam/web/root:/usr/share/nginx/html:ro
        
